version: '3'

services:
  userservice:
    build: Services/UserService
    ports:
      - "5000:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "5000"
      ASPNETCORE_ENVIRONMENT: "Development"
  
  fileservice:
    build: Services/FileService
    ports:
      - "6000:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "6000"
      ASPNETCORE_ENVIRONMENT: "Development"
  
  envoy:
    build: ApiGateway/
    ports: 
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./ApiGateway/envoy.yaml:/etc/envoy/envoy.yaml

  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"