version: '3.1'
services:
  user_service:
    container_name: user_service
    build: ./UserService/
    ports:
      - "8000:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "8000"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
       - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - user_service_db
  user_service_db:
    container_name: user_service_db
    image: postgres:10-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
       - ./PostgresData:/var/lib/postgresql/data
  file_service:
    container_name: file_service
    build: ./FileService
    ports:
      - "8001:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
       - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - file_service_db
  file_service_db:
    container_name: file_service_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
       - ./MongoData:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"