version: '3.1'
services:
  user_service:
    container_name: file_service
    build: .
    ports:
      - "8001:80"
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
       - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db
  db:
    container_name: file_service_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
       - ./MongoData:/data/db